spring.application.name=backend

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/todolist
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=qwerty

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Groq
groq.api.key=your_groq_api_key_here
groq.api.url=https://api.groq.com/openai/v1/chat/completions